const mobNames = new Map<string, string>([
  ['npc1', 'Villager'],
  ['npc2', 'Priest'],
  ['npc3', 'Guard'],
  ['npc4', 'Runemaster'],
  ['acidEle1', 'Acid Elemental'],
  ['acidEnt1', 'Acid Oak'],
  ['coldEle1', 'Ice Elemental'],
  ['coldEnt1', 'Ice Oak'],
  ['deerBB1', 'Fawn'],
  ['deerF1', 'Deer'],
  ['deerM1', 'Stag'],
  ['elecEle1', 'Lightning Elemental'],
  ['elecEnt1', 'Lightning Oak'],
  ['fairy1', 'Fairy'],
  ['fireEle1', 'Fire Elemental'],
  ['fireEnt1', 'Fire Oak'],
  ['flyingFairy1', 'Flying Fairy'],
  ['goo1', 'Goo'],
  ['bouncyGoo1', 'Bouncy Goo'],
  ['giantGoo1', 'Giant Goo'],
  ['kingGoo1', 'King Goo'],
  ['kingSpikedGoo1', 'King Spiked Goo'],
  ['spikedGoo1', 'Spiked Goo'],
  ['giantSpikedGoo1', 'Spiked Goo'],
  ['minotaur1', 'Minotaur'],
  ['wolf1', 'Wolf'],
  ['myconidLg1', 'Myconid'],
  ['myconidSm1', 'Myconid'],
  ['nutcracker1', 'Nutcracker'],
  ['orcRanger1', 'Orc Ranger'],
  ['orcWarrior1', 'Orc Warrior'],
  ['physEle1', 'Earth Elemental'],
  ['physEnt1', 'Oak'],
  ['shrub1', 'Shrub'],
  ['shrub2', 'Shrub'],
  ['squirrel1', 'Squirrel'],
  ['squirrel2', 'Squirrel'],
  ['walrus1', 'Walrus'],
])

export default function getMobName(md: string) {
  return mobNames.get(md) ?? md
}
